-- App Platform *dev* databases have no SQL console — you cannot run GRANT yourself.
-- Leave DATABASE_SCHEMA unset in the API app and use the default `public` schema.
-- If you still see "permission denied for schema public", either:
--   • Convert the component to a Managed PostgreSQL (SQL access + full roles), or
--   • Remove and re-add the dev database after a successful deploy (per DO support docs).
--
-- If you use standalone Managed PostgreSQL with an admin user, you may run:
--   GRANT CREATE ON DATABASE "your-db" TO "your-app-user";
--   -- and/or
--   GRANT ALL PRIVILEGES ON SCHEMA public TO "your-app-user";
