// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: identity.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeMobileOAuthExchange = `-- name: ConsumeMobileOAuthExchange :one
UPDATE mobile_oauth_exchanges
SET consumed_at = NOW()
WHERE code = $1
  AND consumed_at IS NULL
  AND expires_at > NOW()
RETURNING code, user_id, encrypted_payload, expires_at, consumed_at, created_at
`

func (q *Queries) ConsumeMobileOAuthExchange(ctx context.Context, code string) (MobileOauthExchange, error) {
	row := q.db.QueryRow(ctx, consumeMobileOAuthExchange, code)
	var i MobileOauthExchange
	err := row.Scan(
		&i.Code,
		&i.UserID,
		&i.EncryptedPayload,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMobileOAuthExchange = `-- name: CreateMobileOAuthExchange :one
INSERT INTO mobile_oauth_exchanges (
    code,
    user_id,
    encrypted_payload,
    expires_at
) VALUES ($1, $2, $3, $4)
RETURNING code, user_id, encrypted_payload, expires_at, consumed_at, created_at
`

type CreateMobileOAuthExchangeParams struct {
	Code             string             `json:"code"`
	UserID           string             `json:"user_id"`
	EncryptedPayload []byte             `json:"encrypted_payload"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMobileOAuthExchange(ctx context.Context, arg CreateMobileOAuthExchangeParams) (MobileOauthExchange, error) {
	row := q.db.QueryRow(ctx, createMobileOAuthExchange,
		arg.Code,
		arg.UserID,
		arg.EncryptedPayload,
		arg.ExpiresAt,
	)
	var i MobileOauthExchange
	err := row.Scan(
		&i.Code,
		&i.UserID,
		&i.EncryptedPayload,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredMobileOAuthExchanges = `-- name: DeleteExpiredMobileOAuthExchanges :exec
DELETE FROM mobile_oauth_exchanges
WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredMobileOAuthExchanges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredMobileOAuthExchanges)
	return err
}
