// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Apartado struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          string             `json:"user_id"`
	FinancialGoalID pgtype.UUID        `json:"financial_goal_id"`
	Name            string             `json:"name"`
	Description     string             `json:"description"`
	CurrencyCode    string             `json:"currency_code"`
	CurrentUnits    int64              `json:"current_units"`
	CurrentNanos    int32              `json:"current_nanos"`
	TargetUnits     int64              `json:"target_units"`
	TargetNanos     int32              `json:"target_nanos"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Expense struct {
	ID                    pgtype.UUID        `json:"id"`
	UserID                string             `json:"user_id"`
	ReceiptID             pgtype.UUID        `json:"receipt_id"`
	EncryptedMerchantName []byte             `json:"encrypted_merchant_name"`
	MerchantHash          string             `json:"merchant_hash"`
	EncryptedDisplayTitle []byte             `json:"encrypted_display_title"`
	Category              string             `json:"category"`
	CurrencyCode          string             `json:"currency_code"`
	AmountUnits           int64              `json:"amount_units"`
	AmountNanos           int32              `json:"amount_nanos"`
	OccurredAt            pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type FinancialGoal struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             string             `json:"user_id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	TargetCurrencyCode string             `json:"target_currency_code"`
	TargetUnits        int64              `json:"target_units"`
	TargetNanos        int32              `json:"target_nanos"`
	TargetDate         pgtype.Timestamptz `json:"target_date"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type MobileOauthExchange struct {
	Code             string             `json:"code"`
	UserID           string             `json:"user_id"`
	EncryptedPayload []byte             `json:"encrypted_payload"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ReceiptExtraction struct {
	ReceiptID             pgtype.UUID        `json:"receipt_id"`
	Status                string             `json:"status"`
	EncryptedMerchantName []byte             `json:"encrypted_merchant_name"`
	MerchantHash          string             `json:"merchant_hash"`
	EncryptedRedactedText []byte             `json:"encrypted_redacted_text"`
	DocumentFingerprint   string             `json:"document_fingerprint"`
	SuggestedCategory     string             `json:"suggested_category"`
	PurchasedAt           pgtype.Timestamptz `json:"purchased_at"`
	TotalCurrency         string             `json:"total_currency"`
	TotalUnits            int64              `json:"total_units"`
	TotalNanos            int32              `json:"total_nanos"`
	LineItems             []byte             `json:"line_items"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type ReceiptUpload struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           string             `json:"user_id"`
	ObjectKey        string             `json:"object_key"`
	Filename         string             `json:"filename"`
	MimeType         string             `json:"mime_type"`
	EncryptedDataKey []byte             `json:"encrypted_data_key"`
	KeyNonce         []byte             `json:"key_nonce"`
	ContentSha256    string             `json:"content_sha256"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type RecurringPaymentReminder struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             string             `json:"user_id"`
	Title              string             `json:"title"`
	Payee              string             `json:"payee"`
	AmountCurrencyCode string             `json:"amount_currency_code"`
	AmountUnits        int64              `json:"amount_units"`
	AmountNanos        int32              `json:"amount_nanos"`
	Frequency          string             `json:"frequency"`
	Interval           int32              `json:"interval"`
	DayOfWeek          pgtype.Int4        `json:"day_of_week"`
	DayOfMonth         pgtype.Int4        `json:"day_of_month"`
	MonthOfYear        pgtype.Int4        `json:"month_of_year"`
	LocalTime          string             `json:"local_time"`
	Timezone           string             `json:"timezone"`
	NextDueAt          pgtype.Timestamptz `json:"next_due_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type ScoreSnapshot struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    string             `json:"user_id"`
	Score     int32              `json:"score"`
	Factors   []byte             `json:"factors"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
