// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	ConsumeMobileOAuthExchange(ctx context.Context, code string) (MobileOauthExchange, error)
	CreateMobileOAuthExchange(ctx context.Context, arg CreateMobileOAuthExchangeParams) (MobileOauthExchange, error)
	DeleteExpiredMobileOAuthExchanges(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
