// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Expense struct {
	ID                    uuid.UUID          `json:"id"`
	UserID                string             `json:"user_id"`
	ReceiptID             pgtype.UUID        `json:"receipt_id"`
	EncryptedMerchantName []byte             `json:"encrypted_merchant_name"`
	MerchantHash          string             `json:"merchant_hash"`
	EncryptedDisplayTitle []byte             `json:"encrypted_display_title"`
	Category              string             `json:"category"`
	CurrencyCode          string             `json:"currency_code"`
	AmountUnits           int64              `json:"amount_units"`
	AmountNanos           int32              `json:"amount_nanos"`
	OccurredAt            pgtype.Timestamptz `json:"occurred_at"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
}

type MobileOauthExchange struct {
	Code             string             `json:"code"`
	UserID           string             `json:"user_id"`
	EncryptedPayload []byte             `json:"encrypted_payload"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt       pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ReceiptExtraction struct {
	ReceiptID             uuid.UUID          `json:"receipt_id"`
	Status                string             `json:"status"`
	EncryptedMerchantName []byte             `json:"encrypted_merchant_name"`
	MerchantHash          string             `json:"merchant_hash"`
	EncryptedRedactedText []byte             `json:"encrypted_redacted_text"`
	DocumentFingerprint   string             `json:"document_fingerprint"`
	SuggestedCategory     string             `json:"suggested_category"`
	PurchasedAt           pgtype.Timestamptz `json:"purchased_at"`
	TotalCurrency         string             `json:"total_currency"`
	TotalUnits            int64              `json:"total_units"`
	TotalNanos            int32              `json:"total_nanos"`
	LineItems             json.RawMessage    `json:"line_items"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type ReceiptUpload struct {
	ID               uuid.UUID          `json:"id"`
	UserID           string             `json:"user_id"`
	ObjectKey        string             `json:"object_key"`
	Filename         string             `json:"filename"`
	MimeType         string             `json:"mime_type"`
	EncryptedDataKey []byte             `json:"encrypted_data_key"`
	KeyNonce         []byte             `json:"key_nonce"`
	ContentSha256    string             `json:"content_sha256"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type ScoreSnapshot struct {
	ID        uuid.UUID          `json:"id"`
	UserID    string             `json:"user_id"`
	Score     int32              `json:"score"`
	Factors   json.RawMessage    `json:"factors"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
