// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	ClearFinancialGoalLinks(ctx context.Context, arg ClearFinancialGoalLinksParams) error
	CreateApartado(ctx context.Context, arg CreateApartadoParams) (Apartado, error)
	CreateFinancialGoal(ctx context.Context, arg CreateFinancialGoalParams) (FinancialGoal, error)
	CreateRecurringPaymentReminder(ctx context.Context, arg CreateRecurringPaymentReminderParams) (RecurringPaymentReminder, error)
	DeleteApartado(ctx context.Context, arg DeleteApartadoParams) (Apartado, error)
	DeleteFinancialGoal(ctx context.Context, arg DeleteFinancialGoalParams) (FinancialGoal, error)
	DeleteRecurringPaymentReminder(ctx context.Context, arg DeleteRecurringPaymentReminderParams) (RecurringPaymentReminder, error)
	GetApartado(ctx context.Context, arg GetApartadoParams) (Apartado, error)
	GetFinancialGoal(ctx context.Context, arg GetFinancialGoalParams) (FinancialGoal, error)
	GetRecurringPaymentReminder(ctx context.Context, arg GetRecurringPaymentReminderParams) (RecurringPaymentReminder, error)
	ListApartados(ctx context.Context, arg ListApartadosParams) ([]Apartado, error)
	ListFinancialGoalCurrentAmounts(ctx context.Context, userID string) ([]ListFinancialGoalCurrentAmountsRow, error)
	ListFinancialGoals(ctx context.Context, arg ListFinancialGoalsParams) ([]FinancialGoal, error)
	ListRecurringPaymentReminders(ctx context.Context, arg ListRecurringPaymentRemindersParams) ([]RecurringPaymentReminder, error)
	UpdateApartado(ctx context.Context, arg UpdateApartadoParams) (Apartado, error)
	UpdateFinancialGoal(ctx context.Context, arg UpdateFinancialGoalParams) (FinancialGoal, error)
	UpdateRecurringPaymentReminder(ctx context.Context, arg UpdateRecurringPaymentReminderParams) (RecurringPaymentReminder, error)
}

var _ Querier = (*Queries)(nil)
