// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: savings.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearFinancialGoalLinks = `-- name: ClearFinancialGoalLinks :exec
UPDATE apartados
SET
    financial_goal_id = NULL,
    updated_at = NOW()
WHERE user_id = $1
  AND financial_goal_id = $2
  AND deleted_at IS NULL
`

type ClearFinancialGoalLinksParams struct {
	UserID          string      `json:"user_id"`
	FinancialGoalID pgtype.UUID `json:"financial_goal_id"`
}

func (q *Queries) ClearFinancialGoalLinks(ctx context.Context, arg ClearFinancialGoalLinksParams) error {
	_, err := q.db.Exec(ctx, clearFinancialGoalLinks, arg.UserID, arg.FinancialGoalID)
	return err
}

const createApartado = `-- name: CreateApartado :one
INSERT INTO apartados (
    user_id,
    financial_goal_id,
    name,
    description,
    currency_code,
    current_units,
    current_nanos,
    target_units,
    target_nanos
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, user_id, financial_goal_id, name, description, currency_code, current_units, current_nanos, target_units, target_nanos, created_at, updated_at, deleted_at
`

type CreateApartadoParams struct {
	UserID          string      `json:"user_id"`
	FinancialGoalID pgtype.UUID `json:"financial_goal_id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	CurrencyCode    string      `json:"currency_code"`
	CurrentUnits    int64       `json:"current_units"`
	CurrentNanos    int32       `json:"current_nanos"`
	TargetUnits     int64       `json:"target_units"`
	TargetNanos     int32       `json:"target_nanos"`
}

func (q *Queries) CreateApartado(ctx context.Context, arg CreateApartadoParams) (Apartado, error) {
	row := q.db.QueryRow(ctx, createApartado,
		arg.UserID,
		arg.FinancialGoalID,
		arg.Name,
		arg.Description,
		arg.CurrencyCode,
		arg.CurrentUnits,
		arg.CurrentNanos,
		arg.TargetUnits,
		arg.TargetNanos,
	)
	var i Apartado
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FinancialGoalID,
		&i.Name,
		&i.Description,
		&i.CurrencyCode,
		&i.CurrentUnits,
		&i.CurrentNanos,
		&i.TargetUnits,
		&i.TargetNanos,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createFinancialGoal = `-- name: CreateFinancialGoal :one
INSERT INTO financial_goals (
    user_id,
    name,
    description,
    target_currency_code,
    target_units,
    target_nanos,
    target_date
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, name, description, target_currency_code, target_units, target_nanos, target_date, created_at, updated_at, deleted_at
`

type CreateFinancialGoalParams struct {
	UserID             string             `json:"user_id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	TargetCurrencyCode string             `json:"target_currency_code"`
	TargetUnits        int64              `json:"target_units"`
	TargetNanos        int32              `json:"target_nanos"`
	TargetDate         pgtype.Timestamptz `json:"target_date"`
}

func (q *Queries) CreateFinancialGoal(ctx context.Context, arg CreateFinancialGoalParams) (FinancialGoal, error) {
	row := q.db.QueryRow(ctx, createFinancialGoal,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.TargetCurrencyCode,
		arg.TargetUnits,
		arg.TargetNanos,
		arg.TargetDate,
	)
	var i FinancialGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.TargetCurrencyCode,
		&i.TargetUnits,
		&i.TargetNanos,
		&i.TargetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createRecurringPaymentReminder = `-- name: CreateRecurringPaymentReminder :one
INSERT INTO recurring_payment_reminders (
    user_id,
    title,
    payee,
    amount_currency_code,
    amount_units,
    amount_nanos,
    frequency,
    interval,
    day_of_week,
    day_of_month,
    month_of_year,
    local_time,
    timezone,
    next_due_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
RETURNING id, user_id, title, payee, amount_currency_code, amount_units, amount_nanos, frequency, interval, day_of_week, day_of_month, month_of_year, local_time, timezone, next_due_at, created_at, updated_at, deleted_at
`

type CreateRecurringPaymentReminderParams struct {
	UserID             string             `json:"user_id"`
	Title              string             `json:"title"`
	Payee              string             `json:"payee"`
	AmountCurrencyCode string             `json:"amount_currency_code"`
	AmountUnits        int64              `json:"amount_units"`
	AmountNanos        int32              `json:"amount_nanos"`
	Frequency          string             `json:"frequency"`
	Interval           int32              `json:"interval"`
	DayOfWeek          pgtype.Int4        `json:"day_of_week"`
	DayOfMonth         pgtype.Int4        `json:"day_of_month"`
	MonthOfYear        pgtype.Int4        `json:"month_of_year"`
	LocalTime          string             `json:"local_time"`
	Timezone           string             `json:"timezone"`
	NextDueAt          pgtype.Timestamptz `json:"next_due_at"`
}

func (q *Queries) CreateRecurringPaymentReminder(ctx context.Context, arg CreateRecurringPaymentReminderParams) (RecurringPaymentReminder, error) {
	row := q.db.QueryRow(ctx, createRecurringPaymentReminder,
		arg.UserID,
		arg.Title,
		arg.Payee,
		arg.AmountCurrencyCode,
		arg.AmountUnits,
		arg.AmountNanos,
		arg.Frequency,
		arg.Interval,
		arg.DayOfWeek,
		arg.DayOfMonth,
		arg.MonthOfYear,
		arg.LocalTime,
		arg.Timezone,
		arg.NextDueAt,
	)
	var i RecurringPaymentReminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Payee,
		&i.AmountCurrencyCode,
		&i.AmountUnits,
		&i.AmountNanos,
		&i.Frequency,
		&i.Interval,
		&i.DayOfWeek,
		&i.DayOfMonth,
		&i.MonthOfYear,
		&i.LocalTime,
		&i.Timezone,
		&i.NextDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteApartado = `-- name: DeleteApartado :one
UPDATE apartados
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE user_id = $1
  AND id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, financial_goal_id, name, description, currency_code, current_units, current_nanos, target_units, target_nanos, created_at, updated_at, deleted_at
`

type DeleteApartadoParams struct {
	UserID string    `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) DeleteApartado(ctx context.Context, arg DeleteApartadoParams) (Apartado, error) {
	row := q.db.QueryRow(ctx, deleteApartado, arg.UserID, arg.ID)
	var i Apartado
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FinancialGoalID,
		&i.Name,
		&i.Description,
		&i.CurrencyCode,
		&i.CurrentUnits,
		&i.CurrentNanos,
		&i.TargetUnits,
		&i.TargetNanos,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteFinancialGoal = `-- name: DeleteFinancialGoal :one
UPDATE financial_goals
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE user_id = $1
  AND id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, name, description, target_currency_code, target_units, target_nanos, target_date, created_at, updated_at, deleted_at
`

type DeleteFinancialGoalParams struct {
	UserID string    `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) DeleteFinancialGoal(ctx context.Context, arg DeleteFinancialGoalParams) (FinancialGoal, error) {
	row := q.db.QueryRow(ctx, deleteFinancialGoal, arg.UserID, arg.ID)
	var i FinancialGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.TargetCurrencyCode,
		&i.TargetUnits,
		&i.TargetNanos,
		&i.TargetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRecurringPaymentReminder = `-- name: DeleteRecurringPaymentReminder :one
UPDATE recurring_payment_reminders
SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE user_id = $1
  AND id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, title, payee, amount_currency_code, amount_units, amount_nanos, frequency, interval, day_of_week, day_of_month, month_of_year, local_time, timezone, next_due_at, created_at, updated_at, deleted_at
`

type DeleteRecurringPaymentReminderParams struct {
	UserID string    `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) DeleteRecurringPaymentReminder(ctx context.Context, arg DeleteRecurringPaymentReminderParams) (RecurringPaymentReminder, error) {
	row := q.db.QueryRow(ctx, deleteRecurringPaymentReminder, arg.UserID, arg.ID)
	var i RecurringPaymentReminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Payee,
		&i.AmountCurrencyCode,
		&i.AmountUnits,
		&i.AmountNanos,
		&i.Frequency,
		&i.Interval,
		&i.DayOfWeek,
		&i.DayOfMonth,
		&i.MonthOfYear,
		&i.LocalTime,
		&i.Timezone,
		&i.NextDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getApartado = `-- name: GetApartado :one
SELECT id, user_id, financial_goal_id, name, description, currency_code, current_units, current_nanos, target_units, target_nanos, created_at, updated_at, deleted_at
FROM apartados
WHERE user_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetApartadoParams struct {
	UserID string    `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetApartado(ctx context.Context, arg GetApartadoParams) (Apartado, error) {
	row := q.db.QueryRow(ctx, getApartado, arg.UserID, arg.ID)
	var i Apartado
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FinancialGoalID,
		&i.Name,
		&i.Description,
		&i.CurrencyCode,
		&i.CurrentUnits,
		&i.CurrentNanos,
		&i.TargetUnits,
		&i.TargetNanos,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFinancialGoal = `-- name: GetFinancialGoal :one
SELECT id, user_id, name, description, target_currency_code, target_units, target_nanos, target_date, created_at, updated_at, deleted_at
FROM financial_goals
WHERE user_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetFinancialGoalParams struct {
	UserID string    `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetFinancialGoal(ctx context.Context, arg GetFinancialGoalParams) (FinancialGoal, error) {
	row := q.db.QueryRow(ctx, getFinancialGoal, arg.UserID, arg.ID)
	var i FinancialGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.TargetCurrencyCode,
		&i.TargetUnits,
		&i.TargetNanos,
		&i.TargetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRecurringPaymentReminder = `-- name: GetRecurringPaymentReminder :one
SELECT id, user_id, title, payee, amount_currency_code, amount_units, amount_nanos, frequency, interval, day_of_week, day_of_month, month_of_year, local_time, timezone, next_due_at, created_at, updated_at, deleted_at
FROM recurring_payment_reminders
WHERE user_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetRecurringPaymentReminderParams struct {
	UserID string    `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) GetRecurringPaymentReminder(ctx context.Context, arg GetRecurringPaymentReminderParams) (RecurringPaymentReminder, error) {
	row := q.db.QueryRow(ctx, getRecurringPaymentReminder, arg.UserID, arg.ID)
	var i RecurringPaymentReminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Payee,
		&i.AmountCurrencyCode,
		&i.AmountUnits,
		&i.AmountNanos,
		&i.Frequency,
		&i.Interval,
		&i.DayOfWeek,
		&i.DayOfMonth,
		&i.MonthOfYear,
		&i.LocalTime,
		&i.Timezone,
		&i.NextDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listApartados = `-- name: ListApartados :many
SELECT id, user_id, financial_goal_id, name, description, currency_code, current_units, current_nanos, target_units, target_nanos, created_at, updated_at, deleted_at
FROM apartados
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListApartadosParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListApartados(ctx context.Context, arg ListApartadosParams) ([]Apartado, error) {
	rows, err := q.db.Query(ctx, listApartados, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Apartado
	for rows.Next() {
		var i Apartado
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FinancialGoalID,
			&i.Name,
			&i.Description,
			&i.CurrencyCode,
			&i.CurrentUnits,
			&i.CurrentNanos,
			&i.TargetUnits,
			&i.TargetNanos,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinancialGoalCurrentAmounts = `-- name: ListFinancialGoalCurrentAmounts :many
SELECT
    financial_goal_id,
    COALESCE(SUM(current_units * 1000000000::bigint + current_nanos::bigint), 0)::bigint AS total_nanos
FROM apartados
WHERE user_id = $1
  AND deleted_at IS NULL
  AND financial_goal_id IS NOT NULL
GROUP BY financial_goal_id
`

type ListFinancialGoalCurrentAmountsRow struct {
	FinancialGoalID pgtype.UUID `json:"financial_goal_id"`
	TotalNanos      int64       `json:"total_nanos"`
}

func (q *Queries) ListFinancialGoalCurrentAmounts(ctx context.Context, userID string) ([]ListFinancialGoalCurrentAmountsRow, error) {
	rows, err := q.db.Query(ctx, listFinancialGoalCurrentAmounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFinancialGoalCurrentAmountsRow
	for rows.Next() {
		var i ListFinancialGoalCurrentAmountsRow
		if err := rows.Scan(&i.FinancialGoalID, &i.TotalNanos); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFinancialGoals = `-- name: ListFinancialGoals :many
SELECT id, user_id, name, description, target_currency_code, target_units, target_nanos, target_date, created_at, updated_at, deleted_at
FROM financial_goals
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListFinancialGoalsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListFinancialGoals(ctx context.Context, arg ListFinancialGoalsParams) ([]FinancialGoal, error) {
	rows, err := q.db.Query(ctx, listFinancialGoals, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FinancialGoal
	for rows.Next() {
		var i FinancialGoal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.TargetCurrencyCode,
			&i.TargetUnits,
			&i.TargetNanos,
			&i.TargetDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringPaymentReminders = `-- name: ListRecurringPaymentReminders :many
SELECT id, user_id, title, payee, amount_currency_code, amount_units, amount_nanos, frequency, interval, day_of_week, day_of_month, month_of_year, local_time, timezone, next_due_at, created_at, updated_at, deleted_at
FROM recurring_payment_reminders
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2
`

type ListRecurringPaymentRemindersParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListRecurringPaymentReminders(ctx context.Context, arg ListRecurringPaymentRemindersParams) ([]RecurringPaymentReminder, error) {
	rows, err := q.db.Query(ctx, listRecurringPaymentReminders, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringPaymentReminder
	for rows.Next() {
		var i RecurringPaymentReminder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Payee,
			&i.AmountCurrencyCode,
			&i.AmountUnits,
			&i.AmountNanos,
			&i.Frequency,
			&i.Interval,
			&i.DayOfWeek,
			&i.DayOfMonth,
			&i.MonthOfYear,
			&i.LocalTime,
			&i.Timezone,
			&i.NextDueAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateApartado = `-- name: UpdateApartado :one
UPDATE apartados
SET
    financial_goal_id = $3,
    name = $4,
    description = $5,
    currency_code = $6,
    current_units = $7,
    current_nanos = $8,
    target_units = $9,
    target_nanos = $10,
    updated_at = NOW()
WHERE user_id = $1
  AND id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, financial_goal_id, name, description, currency_code, current_units, current_nanos, target_units, target_nanos, created_at, updated_at, deleted_at
`

type UpdateApartadoParams struct {
	UserID          string      `json:"user_id"`
	ID              uuid.UUID   `json:"id"`
	FinancialGoalID pgtype.UUID `json:"financial_goal_id"`
	Name            string      `json:"name"`
	Description     string      `json:"description"`
	CurrencyCode    string      `json:"currency_code"`
	CurrentUnits    int64       `json:"current_units"`
	CurrentNanos    int32       `json:"current_nanos"`
	TargetUnits     int64       `json:"target_units"`
	TargetNanos     int32       `json:"target_nanos"`
}

func (q *Queries) UpdateApartado(ctx context.Context, arg UpdateApartadoParams) (Apartado, error) {
	row := q.db.QueryRow(ctx, updateApartado,
		arg.UserID,
		arg.ID,
		arg.FinancialGoalID,
		arg.Name,
		arg.Description,
		arg.CurrencyCode,
		arg.CurrentUnits,
		arg.CurrentNanos,
		arg.TargetUnits,
		arg.TargetNanos,
	)
	var i Apartado
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FinancialGoalID,
		&i.Name,
		&i.Description,
		&i.CurrencyCode,
		&i.CurrentUnits,
		&i.CurrentNanos,
		&i.TargetUnits,
		&i.TargetNanos,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateFinancialGoal = `-- name: UpdateFinancialGoal :one
UPDATE financial_goals
SET
    name = $3,
    description = $4,
    target_currency_code = $5,
    target_units = $6,
    target_nanos = $7,
    target_date = $8,
    updated_at = NOW()
WHERE user_id = $1
  AND id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, name, description, target_currency_code, target_units, target_nanos, target_date, created_at, updated_at, deleted_at
`

type UpdateFinancialGoalParams struct {
	UserID             string             `json:"user_id"`
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Description        string             `json:"description"`
	TargetCurrencyCode string             `json:"target_currency_code"`
	TargetUnits        int64              `json:"target_units"`
	TargetNanos        int32              `json:"target_nanos"`
	TargetDate         pgtype.Timestamptz `json:"target_date"`
}

func (q *Queries) UpdateFinancialGoal(ctx context.Context, arg UpdateFinancialGoalParams) (FinancialGoal, error) {
	row := q.db.QueryRow(ctx, updateFinancialGoal,
		arg.UserID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TargetCurrencyCode,
		arg.TargetUnits,
		arg.TargetNanos,
		arg.TargetDate,
	)
	var i FinancialGoal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.TargetCurrencyCode,
		&i.TargetUnits,
		&i.TargetNanos,
		&i.TargetDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateRecurringPaymentReminder = `-- name: UpdateRecurringPaymentReminder :one
UPDATE recurring_payment_reminders
SET
    title = $3,
    payee = $4,
    amount_currency_code = $5,
    amount_units = $6,
    amount_nanos = $7,
    frequency = $8,
    interval = $9,
    day_of_week = $10,
    day_of_month = $11,
    month_of_year = $12,
    local_time = $13,
    timezone = $14,
    next_due_at = $15,
    updated_at = NOW()
WHERE user_id = $1
  AND id = $2
  AND deleted_at IS NULL
RETURNING id, user_id, title, payee, amount_currency_code, amount_units, amount_nanos, frequency, interval, day_of_week, day_of_month, month_of_year, local_time, timezone, next_due_at, created_at, updated_at, deleted_at
`

type UpdateRecurringPaymentReminderParams struct {
	UserID             string             `json:"user_id"`
	ID                 uuid.UUID          `json:"id"`
	Title              string             `json:"title"`
	Payee              string             `json:"payee"`
	AmountCurrencyCode string             `json:"amount_currency_code"`
	AmountUnits        int64              `json:"amount_units"`
	AmountNanos        int32              `json:"amount_nanos"`
	Frequency          string             `json:"frequency"`
	Interval           int32              `json:"interval"`
	DayOfWeek          pgtype.Int4        `json:"day_of_week"`
	DayOfMonth         pgtype.Int4        `json:"day_of_month"`
	MonthOfYear        pgtype.Int4        `json:"month_of_year"`
	LocalTime          string             `json:"local_time"`
	Timezone           string             `json:"timezone"`
	NextDueAt          pgtype.Timestamptz `json:"next_due_at"`
}

func (q *Queries) UpdateRecurringPaymentReminder(ctx context.Context, arg UpdateRecurringPaymentReminderParams) (RecurringPaymentReminder, error) {
	row := q.db.QueryRow(ctx, updateRecurringPaymentReminder,
		arg.UserID,
		arg.ID,
		arg.Title,
		arg.Payee,
		arg.AmountCurrencyCode,
		arg.AmountUnits,
		arg.AmountNanos,
		arg.Frequency,
		arg.Interval,
		arg.DayOfWeek,
		arg.DayOfMonth,
		arg.MonthOfYear,
		arg.LocalTime,
		arg.Timezone,
		arg.NextDueAt,
	)
	var i RecurringPaymentReminder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Payee,
		&i.AmountCurrencyCode,
		&i.AmountUnits,
		&i.AmountNanos,
		&i.Frequency,
		&i.Interval,
		&i.DayOfWeek,
		&i.DayOfMonth,
		&i.MonthOfYear,
		&i.LocalTime,
		&i.Timezone,
		&i.NextDueAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
