// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createReceiptUpload = `-- name: CreateReceiptUpload :one
INSERT INTO receipt_uploads (
    user_id,
    object_key,
    filename,
    mime_type,
    encrypted_data_key,
    key_nonce,
    content_sha256
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, object_key, filename, mime_type, encrypted_data_key, key_nonce, content_sha256, created_at
`

type CreateReceiptUploadParams struct {
	UserID           string `json:"user_id"`
	ObjectKey        string `json:"object_key"`
	Filename         string `json:"filename"`
	MimeType         string `json:"mime_type"`
	EncryptedDataKey []byte `json:"encrypted_data_key"`
	KeyNonce         []byte `json:"key_nonce"`
	ContentSha256    string `json:"content_sha256"`
}

func (q *Queries) CreateReceiptUpload(ctx context.Context, arg CreateReceiptUploadParams) (ReceiptUpload, error) {
	row := q.db.QueryRow(ctx, createReceiptUpload,
		arg.UserID,
		arg.ObjectKey,
		arg.Filename,
		arg.MimeType,
		arg.EncryptedDataKey,
		arg.KeyNonce,
		arg.ContentSha256,
	)
	var i ReceiptUpload
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ObjectKey,
		&i.Filename,
		&i.MimeType,
		&i.EncryptedDataKey,
		&i.KeyNonce,
		&i.ContentSha256,
		&i.CreatedAt,
	)
	return i, err
}

const getReceiptDraft = `-- name: GetReceiptDraft :one
SELECT
    receipt_uploads.id, receipt_uploads.user_id, receipt_uploads.object_key, receipt_uploads.filename, receipt_uploads.mime_type, receipt_uploads.encrypted_data_key, receipt_uploads.key_nonce, receipt_uploads.content_sha256, receipt_uploads.created_at,
    receipt_extractions.receipt_id, receipt_extractions.status, receipt_extractions.encrypted_merchant_name, receipt_extractions.merchant_hash, receipt_extractions.encrypted_redacted_text, receipt_extractions.document_fingerprint, receipt_extractions.suggested_category, receipt_extractions.purchased_at, receipt_extractions.total_currency, receipt_extractions.total_units, receipt_extractions.total_nanos, receipt_extractions.line_items, receipt_extractions.created_at, receipt_extractions.updated_at
FROM receipt_uploads
JOIN receipt_extractions ON receipt_extractions.receipt_id = receipt_uploads.id
WHERE receipt_uploads.user_id = $1
  AND receipt_uploads.id = $2
`

type GetReceiptDraftParams struct {
	UserID string    `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

type GetReceiptDraftRow struct {
	ReceiptUpload     ReceiptUpload     `json:"receipt_upload"`
	ReceiptExtraction ReceiptExtraction `json:"receipt_extraction"`
}

func (q *Queries) GetReceiptDraft(ctx context.Context, arg GetReceiptDraftParams) (GetReceiptDraftRow, error) {
	row := q.db.QueryRow(ctx, getReceiptDraft, arg.UserID, arg.ID)
	var i GetReceiptDraftRow
	err := row.Scan(
		&i.ReceiptUpload.ID,
		&i.ReceiptUpload.UserID,
		&i.ReceiptUpload.ObjectKey,
		&i.ReceiptUpload.Filename,
		&i.ReceiptUpload.MimeType,
		&i.ReceiptUpload.EncryptedDataKey,
		&i.ReceiptUpload.KeyNonce,
		&i.ReceiptUpload.ContentSha256,
		&i.ReceiptUpload.CreatedAt,
		&i.ReceiptExtraction.ReceiptID,
		&i.ReceiptExtraction.Status,
		&i.ReceiptExtraction.EncryptedMerchantName,
		&i.ReceiptExtraction.MerchantHash,
		&i.ReceiptExtraction.EncryptedRedactedText,
		&i.ReceiptExtraction.DocumentFingerprint,
		&i.ReceiptExtraction.SuggestedCategory,
		&i.ReceiptExtraction.PurchasedAt,
		&i.ReceiptExtraction.TotalCurrency,
		&i.ReceiptExtraction.TotalUnits,
		&i.ReceiptExtraction.TotalNanos,
		&i.ReceiptExtraction.LineItems,
		&i.ReceiptExtraction.CreatedAt,
		&i.ReceiptExtraction.UpdatedAt,
	)
	return i, err
}

const listReceiptDrafts = `-- name: ListReceiptDrafts :many
SELECT
    receipt_uploads.id, receipt_uploads.user_id, receipt_uploads.object_key, receipt_uploads.filename, receipt_uploads.mime_type, receipt_uploads.encrypted_data_key, receipt_uploads.key_nonce, receipt_uploads.content_sha256, receipt_uploads.created_at,
    receipt_extractions.receipt_id, receipt_extractions.status, receipt_extractions.encrypted_merchant_name, receipt_extractions.merchant_hash, receipt_extractions.encrypted_redacted_text, receipt_extractions.document_fingerprint, receipt_extractions.suggested_category, receipt_extractions.purchased_at, receipt_extractions.total_currency, receipt_extractions.total_units, receipt_extractions.total_nanos, receipt_extractions.line_items, receipt_extractions.created_at, receipt_extractions.updated_at
FROM receipt_uploads
JOIN receipt_extractions ON receipt_extractions.receipt_id = receipt_uploads.id
WHERE receipt_uploads.user_id = $1
ORDER BY receipt_uploads.created_at DESC
LIMIT $2
`

type ListReceiptDraftsParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

type ListReceiptDraftsRow struct {
	ReceiptUpload     ReceiptUpload     `json:"receipt_upload"`
	ReceiptExtraction ReceiptExtraction `json:"receipt_extraction"`
}

func (q *Queries) ListReceiptDrafts(ctx context.Context, arg ListReceiptDraftsParams) ([]ListReceiptDraftsRow, error) {
	rows, err := q.db.Query(ctx, listReceiptDrafts, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReceiptDraftsRow
	for rows.Next() {
		var i ListReceiptDraftsRow
		if err := rows.Scan(
			&i.ReceiptUpload.ID,
			&i.ReceiptUpload.UserID,
			&i.ReceiptUpload.ObjectKey,
			&i.ReceiptUpload.Filename,
			&i.ReceiptUpload.MimeType,
			&i.ReceiptUpload.EncryptedDataKey,
			&i.ReceiptUpload.KeyNonce,
			&i.ReceiptUpload.ContentSha256,
			&i.ReceiptUpload.CreatedAt,
			&i.ReceiptExtraction.ReceiptID,
			&i.ReceiptExtraction.Status,
			&i.ReceiptExtraction.EncryptedMerchantName,
			&i.ReceiptExtraction.MerchantHash,
			&i.ReceiptExtraction.EncryptedRedactedText,
			&i.ReceiptExtraction.DocumentFingerprint,
			&i.ReceiptExtraction.SuggestedCategory,
			&i.ReceiptExtraction.PurchasedAt,
			&i.ReceiptExtraction.TotalCurrency,
			&i.ReceiptExtraction.TotalUnits,
			&i.ReceiptExtraction.TotalNanos,
			&i.ReceiptExtraction.LineItems,
			&i.ReceiptExtraction.CreatedAt,
			&i.ReceiptExtraction.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReceiptExtraction = `-- name: UpsertReceiptExtraction :one
INSERT INTO receipt_extractions (
    receipt_id,
    status,
    encrypted_merchant_name,
    merchant_hash,
    encrypted_redacted_text,
    document_fingerprint,
    suggested_category,
    purchased_at,
    total_currency,
    total_units,
    total_nanos,
    line_items
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (receipt_id) DO UPDATE
SET
    status = EXCLUDED.status,
    encrypted_merchant_name = EXCLUDED.encrypted_merchant_name,
    merchant_hash = EXCLUDED.merchant_hash,
    encrypted_redacted_text = EXCLUDED.encrypted_redacted_text,
    document_fingerprint = EXCLUDED.document_fingerprint,
    suggested_category = EXCLUDED.suggested_category,
    purchased_at = EXCLUDED.purchased_at,
    total_currency = EXCLUDED.total_currency,
    total_units = EXCLUDED.total_units,
    total_nanos = EXCLUDED.total_nanos,
    line_items = EXCLUDED.line_items,
    updated_at = NOW()
RETURNING receipt_id, status, encrypted_merchant_name, merchant_hash, encrypted_redacted_text, document_fingerprint, suggested_category, purchased_at, total_currency, total_units, total_nanos, line_items, created_at, updated_at
`

type UpsertReceiptExtractionParams struct {
	ReceiptID             uuid.UUID          `json:"receipt_id"`
	Status                string             `json:"status"`
	EncryptedMerchantName []byte             `json:"encrypted_merchant_name"`
	MerchantHash          string             `json:"merchant_hash"`
	EncryptedRedactedText []byte             `json:"encrypted_redacted_text"`
	DocumentFingerprint   string             `json:"document_fingerprint"`
	SuggestedCategory     string             `json:"suggested_category"`
	PurchasedAt           pgtype.Timestamptz `json:"purchased_at"`
	TotalCurrency         string             `json:"total_currency"`
	TotalUnits            int64              `json:"total_units"`
	TotalNanos            int32              `json:"total_nanos"`
	LineItems             json.RawMessage    `json:"line_items"`
}

func (q *Queries) UpsertReceiptExtraction(ctx context.Context, arg UpsertReceiptExtractionParams) (ReceiptExtraction, error) {
	row := q.db.QueryRow(ctx, upsertReceiptExtraction,
		arg.ReceiptID,
		arg.Status,
		arg.EncryptedMerchantName,
		arg.MerchantHash,
		arg.EncryptedRedactedText,
		arg.DocumentFingerprint,
		arg.SuggestedCategory,
		arg.PurchasedAt,
		arg.TotalCurrency,
		arg.TotalUnits,
		arg.TotalNanos,
		arg.LineItems,
	)
	var i ReceiptExtraction
	err := row.Scan(
		&i.ReceiptID,
		&i.Status,
		&i.EncryptedMerchantName,
		&i.MerchantHash,
		&i.EncryptedRedactedText,
		&i.DocumentFingerprint,
		&i.SuggestedCategory,
		&i.PurchasedAt,
		&i.TotalCurrency,
		&i.TotalUnits,
		&i.TotalNanos,
		&i.LineItems,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
