// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"
)

type Querier interface {
	CreateReceiptUpload(ctx context.Context, arg CreateReceiptUploadParams) (ReceiptUpload, error)
	GetReceiptDraft(ctx context.Context, arg GetReceiptDraftParams) (GetReceiptDraftRow, error)
	ListReceiptDrafts(ctx context.Context, arg ListReceiptDraftsParams) ([]ListReceiptDraftsRow, error)
	UpsertReceiptExtraction(ctx context.Context, arg UpsertReceiptExtractionParams) (ReceiptExtraction, error)
}

var _ Querier = (*Queries)(nil)
